//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enter
    {
        public int CodeEmployee { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
        public string TypeEnter { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
